# render.yaml - Fixed deployment configuration for 2025 YouTube processing
services:
  - type: web
    name: video-processing-service
    env: node
    plan: starter
    buildCommand: |
      echo "Starting build process..."
      
      # Update system packages
      apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        build-essential \
        ffmpeg \
        curl \
        wget \
        software-properties-common \
        ca-certificates \
        gnupg \
        lsb-release
      
      echo "System packages installed successfully"
      
      # Update pip to latest version
      python3 -m pip install --upgrade pip setuptools wheel
      
      # Install yt-dlp with all dependencies (critical for 2025)
      echo "Installing yt-dlp..."
      python3 -m pip install --upgrade --force-reinstall yt-dlp
      
      # Also install youtube-dl as fallback
      python3 -m pip install --upgrade youtube-dl
      
      # Verify installations
      echo "Verifying yt-dlp installation..."
      python3 -m yt_dlp --version || {
        echo "yt-dlp installation failed, trying alternative method..."
        python3 -m pip install --upgrade --no-cache-dir yt-dlp
        python3 -m yt_dlp --version
      }
      
      # Create symlinks for easier access
      ln -sf $(which python3) /usr/bin/python3 2>/dev/null || true
      ln -sf /usr/local/bin/yt-dlp /usr/bin/yt-dlp 2>/dev/null || true
      
      # Set Python path
      export PYTHONPATH="/usr/local/lib/python3.*/site-packages:$PYTHONPATH"
      
      # Install Node.js dependencies
      echo "Installing Node.js dependencies..."
      npm ci --only=production
      
      # Verify ffmpeg installation
      ffmpeg -version
      
      echo "Build completed successfully"
      
    startCommand: "npm start"
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MAX_FILE_SIZE
        value: "524288000"  # 500MB
      - key: MAX_PROCESSING_TIME
        value: "1200000"    # 20 minutes (increased for 2025 bot evasion)
      
      # Supabase Configuration (set these in Render dashboard)
      - key: SUPABASE_URL
        sync: false  # Set to: https://qwqvdvhvcroggxndniom.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set to your service key
      
      # Authentication tokens (set these in Render dashboard)
      - key: PROCESSING_SERVICE_TOKEN
        sync: false  # Generate a secure random token
      - key: N8N_WEBHOOK_SECRET
        sync: false  # Your n8n webhook secret
      - key: VIDEO_PROCESSOR_API_KEY
        sync: false  # Additional API key if needed
      
      # Callback configuration
      - key: DEFAULT_CALLBACK_URL
        sync: false  # Your default callback URL
      
      # 2025 Anti-detection settings
      - key: YOUTUBE_MIN_DELAY
        value: "45000"     # Minimum 45s between requests
      - key: YOUTUBE_MAX_RETRIES
        value: "2"         # Max 2 retries per video
      - key: YOUTUBE_BACKOFF_MULTIPLIER
        value: "2"         # Conservative backoff
      
      # Python configuration
      - key: PYTHONPATH
        value: "/usr/local/lib/python3.11/site-packages:/usr/local/lib/python3.10/site-packages"
      - key: PATH
        value: "/usr/local/bin:/usr/bin:/bin"
    
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    
    # Resource allocation optimized for video processing
    disk:
      name: video-temp
      mountPath: /tmp
      sizeGB: 3  # Increased for larger video files
      
    # Environment-specific settings
    preDeployCommand: |
      echo "Pre-deploy: Updating yt-dlp to latest version..."
      python3 -m pip install --upgrade --force-reinstall yt-dlp || true
      echo "Pre-deploy completed"