services:
  - type: web
    name: video-processing-service
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PROCESSING_SERVICE_TOKEN
        sync: false
      - key: N8N_WEBHOOK_SECRET
        value: "7f9d0d2e8a6f4f38a13a2bcf5b6d441b91c9d26e8b72714d2edcf7c4e2a843ke"
      - key: VIDEO_PROCESSOR_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://video-shorts-business-bot.onrender.com,https://n8n-on-render-wf30.onrender.com"
      - key: MAX_FILE_SIZE
        value: "524288000" # 500MB