# render.yaml - Docker-based deployment configuration
services:
  - type: web
    name: video-processing-service
    env: docker
    plan: starter
    
    # Explicitly specify Dockerfile location
    dockerfilePath: ./Dockerfile
    dockerContext: .
    
    # No buildCommand or startCommand needed for Docker
    # Docker will handle everything
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      
      # Enhanced anti-detection settings for 2025
      - key: YOUTUBE_MIN_DELAY
        value: "120000"    # Increased to 2 minutes
      - key: YOUTUBE_MAX_RETRIES
        value: "1"         # Reduced to 1 retry to avoid detection
      - key: YOUTUBE_BACKOFF_MULTIPLIER
        value: "5"         # More aggressive backoff
      - key: YOUTUBE_REQUEST_TIMEOUT
        value: "180000"    # 3 minute timeout
      
      # Supabase Configuration
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      
      # Authentication
      - key: PROCESSING_SERVICE_TOKEN
        sync: false
      - key: N8N_WEBHOOK_SECRET
        sync: false
      
      # Callback configuration
      - key: DEFAULT_CALLBACK_URL
        sync: false
    
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    
    disk:
      name: video-temp
      mountPath: /tmp
      sizeGB: 5  