services:
  - type: web
    name: video-processing-service
    env: node
    repo: https://github.com/Agbscholar/video-processor.git
    buildCommand: npm install  # ← ONLY this line, remove the apt-get commands
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PROCESSING_SERVICE_TOKEN
        generateValue: true
      - key: N8N_CALLBACK_URL
        value: https://n8n-on-render-wf30.onrender.com/webhook/processing-complete
      - key: MAX_FILE_SIZE
        value: 500MB
      - key: MAX_PROCESSING_TIME
        value: 600000
    disk:
      name: video-processing-disk
      mountPath: /tmp
      sizeGB: 10
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
      targetCPUPercent: 70
    healthCheckPath: /health