# render.yaml - Fixed deployment configuration with proper yt-dlp installation
services:
  - type: web
    name: video-processing-service
    env: node
    plan: starter
    buildCommand: |
      # Update system packages
      apt-get update && apt-get install -y \
        python3 \
        python3-pip \
        python3-venv \
        ffmpeg \
        curl \
        wget \
        software-properties-common \
        ca-certificates \
        gnupg \
        lsb-release
      
      # Install yt-dlp properly with all dependencies
      python3 -m pip install --upgrade pip
      python3 -m pip install --upgrade yt-dlp
      
      # Create symlink to ensure yt-dlp is in PATH
      ln -sf /usr/local/bin/yt-dlp /usr/bin/yt-dlp || true
      
      # Verify installation
      yt-dlp --version || python3 -m yt_dlp --version
      
      # Install Node.js dependencies
      npm ci --only=production
      
      echo "Build completed successfully"
      
    startCommand: "npm start"
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MAX_FILE_SIZE
        value: "524288000"  # 500MB
      - key: MAX_PROCESSING_TIME
        value: "600000"     # 10 minutes
      - key: SUPABASE_URL
        sync: false  # Set in dashboard: https://qwqvdvhvcroggxndniom.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false  # Set in dashboard: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      - key: PROCESSING_SERVICE_TOKEN
        sync: false  # Generate a secure token
      - key: N8N_WEBHOOK_SECRET
        sync: false  # Your n8n webhook secret
      - key: DEFAULT_CALLBACK_URL
        sync: false  # Your default callback URL
    
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    
    # Resource allocation for free tier
    disk: 
      name: video-temp
      mountPath: /tmp
      sizeGB: 1